### PR TITLE
Add exome depth outputs, modify TSO output to find individual sample …

### LINKED ISSUE #30: add sample specific zips
https://github.com/moka-guys/duty_csv/blob/51c87943ce6023f437a1e94a3393ccf2f6898ca7/config.py#L88

        "sample_specific_results_zip": {
            "folder": "/results", ## PERHAPS THIS WILL STILL BE SEPERATED INTO PAN NUM SUBFOLDERS??
            "regex": r"^(?:{}).zip$",
        },

also add https://github.com/moka-guys/duty_csv/blob/51c87943ce6023f437a1e94a3393ccf2f6898ca7/config.py#L155
"sample_specific_results_zip": {
                "Via": f"{P_BIOINF_TESTING}/TSO500/%s/",
                "StG": False,
                "subdir": r"Results/",
            },

https://github.com/moka-guys/duty_csv/blob/51c87943ce6023f437a1e94a3393ccf2f6898ca7/config.py#L214
"sample_specific_results_zip": {
                "Via": f"S:/Genetics_Data2/TSO500/%s/",
                "StG": False,
                "subdir": r"Results/",
            },

https://github.com/moka-guys/duty_csv/blob/51c87943ce6023f437a1e94a3393ccf2f6898ca7/duty_csv.py#L645
for filetype in [
            "gene_level_coverage",
            "exon_level_coverage",
            "results_zip",
            "sample_specific_results_zip"
        ]:

### PR DESCRIPTION
**Pull request by RachelDuffin**
…zips and metrics files in new location. Closes #30, #29

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/duty_csv/31)

### CODE REVIEW

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/duty_csv/31)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

___
*[`config.py` line 94 at r2](https://reviewable.io/reviews/moka-guys/duty_csv/31#-NgTj_4B6AYTD37KN2Pj:-NgTj_4B6AYTD37KN2Pk:bdzwmfj) ([raw file](https://github.com/moka-guys/duty_csv/blob/57950b841065e168023732756f4a068b505b7944/config.py#L94)):*
> ```Python
>         "results_zip": {
>             "folder": "/results",
>             "regex": r"\S+(?:{}).zip$",
> ```

Hi Rachel, Not sure what the empty non-capturing group `(?:{})` is doing here - since `{}` is empty, it doesn't add to the pattern. Do you format this regex string and replace `{}` with an actual pattern later in your code?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/duty_csv/31)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[`config.py` line 94 at r2](https://reviewable.io/reviews/moka-guys/duty_csv/31#-NgTj_4B6AYTD37KN2Pj:-NgTkF9B9C26gK9sl3xM:b-myzhgh) ([raw file](https://github.com/moka-guys/duty_csv/blob/57950b841065e168023732756f4a068b505b7944/config.py#L94)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Hi Rachel, Not sure what the empty non-capturing group `(?:{})` is doing here - since `{}` is empty, it doesn't add to the pattern. Do you format this regex string and replace `{}` with an actual pattern later in your code?
</blockquote></details>

Yeah it is replaced with Pan numbers by the other script, duty_csv.py

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/duty_csv/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RachelDuffin)

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/duty_csv/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RachelDuffin)

___
*[`config.py` line 94 at r2](https://reviewable.io/reviews/moka-guys/duty_csv/31#-NgTj_4B6AYTD37KN2Pj:-NgTkSER8HjdgJ1F-cXc:bu3c7pm) ([raw file](https://github.com/moka-guys/duty_csv/blob/57950b841065e168023732756f4a068b505b7944/config.py#L94)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Yeah it is replaced with Pan numbers by the other script, duty_csv.py
</blockquote></details>

that ensures that we only download the non bsps zips

**Pull request merged**
